apiVersion: v1
kind: Service
metadata:
  name: {{ include "llama-stack-operator.metricsServiceName" . }}
  namespace: {{ include "llama-stack-operator.namespace" . }}
  labels:
    {{- include "llama-stack-operator.controllerLabels" . | nindent 4 }}
  annotations:
    {{- include "llama-stack-operator.annotations" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: {{ .Values.service.name }}
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.targetPort }}
  selector:
    {{- include "llama-stack-operator.selectorLabels" . | nindent 4 }}